// Port of Keiyoushi MangaBox/Manganato (Apache-2.0); see NOTICE.md.
function normalizeQuery(q){return String(q||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');}
function parseCatalogue(body){var doc=html(body);return unique(all(doc,function(n){return has(n,'story_item')||has(n,'list-truyen-item-wrap')||has(n,'list-comic-item-wrap');}).map(function(n){var h=first(n,function(x){return x.tag==='h3';}),a=h&&first(h,function(x){return x.tag==='a'&&x.a.href;}),img=first(n,function(x){return x.tag==='img';});return a?item(absolute(a.a.href,SITE+'/'),content(a),img?absolute(img.a['data-src']||img.a.src,SITE+'/'):null):null;}).filter(Boolean),function(x){return x.id;});}
async function search(query,page){return parseCatalogue(await request(SITE+'/search/story/'+encodeURIComponent(normalizeQuery(query))+'?page='+pageNum(page)));}
async function popular(page){return parseCatalogue(await request(SITE+'/manga-list/hot-manga?page='+pageNum(page)));}
async function getHome(){return homeOrder([{title:'Popular manga',items:await popular(1)},{title:'Latest chapters',items:parseCatalogue(await request(SITE+'/manga-list/latest-manga?page=1'))}]);}
function slugOf(url){return pathOf(url).replace(/\/$/,'').split('/').pop();}
async function getDetail(url){url=absolute(url,SITE+'/');var doc=html(await request(url));var area=first(doc,function(n){return has(n,'manga-info-top')||has(n,'panel-story-info');})||doc;var title=first(area,function(n){return n.tag==='h1'||n.tag==='h2';});if(!title)throw new Error('Manganato: title missing; source may have moved');var coverArea=first(doc,function(n){return has(n,'manga-info-pic')||has(n,'info-image');});var img=coverArea&&first(coverArea,function(n){return n.tag==='img';});var desc=first(doc,function(n){return /^(noidungm|panel-story-info-description|contentBox)$/.test(n.a.id||'');});var result=item(url,content(title),img?absolute(img.a.src,url):null);result.description=content(desc);result.status=/completed/i.test(content(area))?'completed':/ongoing/i.test(content(area))?'ongoing':'unknown';result.genres=[];result.studios=[];result.episodes=await getEpisodes(url);return result;}
async function getEpisodes(url){var slug=slugOf(url),data=await request(SITE+'/api/manga/'+encodeURIComponent(slug)+'/chapters?limit=-1',SITE+'/manga/'+slug,true);if(!data.success)throw new Error('Manganato: chapter API did not succeed');return (data.data&&data.data.chapters||[]).filter(function(c){return c.chapter_slug||c.chapterSlug;}).map(function(c){var part=c.chapter_slug||c.chapterSlug;var n=c.chapter_num!=null?c.chapter_num:c.chapterNum;return {id:slug+':'+part,title:c.chapter_name||c.chapterName||'Chapter',number:isFinite(Number(n))?Number(n):null,url:SITE+'/manga/'+encodeURIComponent(slug)+'/'+encodeURIComponent(part),date:c.updated_at||c.updatedAt||null};}).sort(function(a,b){return(a.number||0)-(b.number||0);});}
function literalArray(body,name){var m=body.match(new RegExp('\\b'+name+'\\s*=\\s*(\\[[\\s\\S]*?\\])'));if(!m)return [];try{var a=JSON.parse(m[1]);return Array.isArray(a)?a.filter(function(x){return typeof x==='string';}):[];}catch(e){throw new Error('Manganato: malformed '+name+' list');}}
async function getPages(url){url=absolute(url,SITE+'/');var body=await request(url),images=literalArray(body,'chapterImages'),cdns=literalArray(body,'cdns'),out=[];if(images.length){if(!cdns.length)throw new Error('Manganato: image CDN missing');out=images.map(function(p){return {url:absolute('/'+p.replace(/^\/+/,''),cdns[setting('imageCdn')==='backup'&&cdns.length>1?1:0]+'/'),headers:headers(url)};});}else{var root=html(body),area=first(root,function(n){return has(n,'container-chapter-reader');});if(area)out=all(area,function(n){return n.tag==='img'&&n.a.src;}).map(function(n){return {url:absolute(n.a.src,url),headers:headers(url)};});}if(!out.length)throw new Error('Manganato: no chapter images found');return out;}
function getChapters(url){return getEpisodes(url);}
