// SPDX-License-Identifier: Apache-2.0
// Modified for Zangetsu on 2026-09-15. See NOTICE.md for upstream credits.
// Generated by build.js; edit common.js and the corresponding *-core.js.
var SOURCE_ID="serenity-animegg", NAME="AnimeGG", SITE="https://www.animegg.org", TYPE="anime", VERSION="0.2.4";
// Shared runtime helpers. No Node, DOM, browser cookies or remote code execution.
function text(value) {
  return String(value || '').replace(/<[^>]*>/g, '')
    .replace(/&#x([\da-f]+);/gi, function(_, n) { return String.fromCodePoint(parseInt(n, 16)); })
    .replace(/&#(\d+);/g, function(_, n) { return String.fromCodePoint(+n); })
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
}
function attrs(raw) {
  var out = {}, re = /([^\s=<>/]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g, m;
  while ((m = re.exec(raw))) out[m[1].toLowerCase()] = text(m[2] != null ? m[2] : m[3] != null ? m[3] : m[4] || '');
  return out;
}
// Small non-executing tree parser for the HTML selectors used by these sources.
function html(raw) {
  var root = {tag: '#root', a: {}, children: [], parent: null}, stack = [root];
  var tokens = String(raw).match(/<!--[\s\S]*?-->|<script\b[^>]*>[\s\S]*?<\/script\s*>|<style\b[^>]*>[\s\S]*?<\/style\s*>|<\/?[a-zA-Z][^>]*>|[^<]+/g) || [];
  tokens.forEach(function(t) {
    if (/^<!--|^<(script|style)\b/i.test(t)) return;
    if (/^<\//.test(t)) {
      var end = t.match(/^<\/([^\s>]+)/)[1].toLowerCase();
      for (var i = stack.length - 1; i > 0; i--) if (stack[i].tag === end) { stack.length = i; break; }
      return;
    }
    var parent = stack[stack.length - 1];
    if (t.charAt(0) !== '<') { parent.children.push({tag:'#text', value:text(t), children:[], a:{}, parent:parent}); return; }
    var m = t.match(/^<([^\s/>]+)([\s\S]*?)\/?\s*>$/); if (!m) return;
    var node = {tag:m[1].toLowerCase(), a:attrs(m[2]), children:[], parent:parent}; parent.children.push(node);
    if (!/^(img|input|br|hr|meta|link|source|area|base|embed|param|track|wbr)$/.test(node.tag) && !/\/\s*>$/.test(t)) stack.push(node);
  });
  return root;
}
function all(node, predicate) {
  var out = []; function walk(n) { n.children.forEach(function(c) { if(predicate(c)) out.push(c); walk(c); }); } walk(node); return out;
}
function first(node, predicate) { return all(node, predicate)[0] || null; }
function has(node, cls) { return (' ' + (node.a.class || '') + ' ').indexOf(' ' + cls + ' ') >= 0; }
function content(node) { return node ? (node.tag === '#text' ? node.value : node.children.map(content).join(' ')).replace(/\s+/g,' ').trim() : ''; }
function origin(url) { var m=String(url).match(/^https?:\/\/[^/]+/i); if(!m) throw new Error('Expected HTTP URL'); return m[0]; }
function absolute(url, base) {
  url=text(url); if(/^https?:\/\//i.test(url)) return url;
  if(url.indexOf('//')===0) return 'https:'+url;
  if(!url || /^[a-z][a-z0-9+.-]*:/i.test(url)) throw new Error('Invalid source URL');
  var root=origin(base || SITE), path=url.charAt(0)==='/' ? url : String(base || SITE+'/').split(/[?#]/)[0].replace(/[^/]*$/,'')+url;
  if(/^https?:/.test(path)) path=path.slice(origin(path).length);
  var parts=[]; path.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});
  return root+parts.join('/');
}
function pathOf(url) { return String(url).replace(/^https?:\/\/[^/]+/i,'').split(/[?#]/)[0]; }
function pageNum(p) { p=Math.floor(Number(p)||1); return Math.max(1,p); }
function headers(ref) { return {Referer:ref || SITE+'/'}; }
async function request(url, ref, json) {
  var h=headers(ref); if(json){h.Accept='application/json, text/javascript, */*; q=0.01';h['X-Requested-With']='XMLHttpRequest';}
  var res=await fetch(url,{headers:h,timeoutMs:Number(setting('timeout'))||12000});
  if(res.status<200 || res.status>=300) throw new Error(NAME+': HTTP '+res.status+' from '+origin(url));
  var body=res.body != null ? res.body : await res.text();
  if(json){try{return JSON.parse(body);}catch(e){throw new Error(NAME+': source returned invalid JSON');}}
  if(/<title>\s*(Just a moment|Attention Required)/i.test(body)) throw new Error(NAME+': open the source in the app WebView to complete its browser check');
  return body;
}
function unique(items, key) { var seen={}; return items.filter(function(x){var k=key(x);if(seen[k])return false;seen[k]=true;return true;}); }
function getInfo() { return {name:NAME,lang:'en',baseUrl:SITE,logo:SITE+'/favicon.ico',type:TYPE,version:VERSION}; }
function item(url,title,cover) { return {id:pathOf(url),title:title,url:url,cover:cover || null,coverHeaders:headers(),type:TYPE,sourceId:SOURCE_ID}; }

// SPDX-License-Identifier: Apache-2.0
function languageCode(value){
  var s=String(value||'').trim().toLowerCase().replace(/_/g,'-');
  var names={english:'en',eng:'en',japanese:'ja',jpn:'ja',chinese:'zh',mandarin:'zh',chi:'zh',zho:'zh',korean:'ko',kor:'ko',hindi:'hi',hin:'hi',spanish:'es',spa:'es',french:'fr',fre:'fr',fra:'fr',german:'de',ger:'de',deu:'de',portuguese:'pt',por:'pt',russian:'ru',rus:'ru',arabic:'ar',ara:'ar',italian:'it',ita:'it',tamil:'ta',tam:'ta',telugu:'te',tel:'te'};
  if(names[s])return names[s];return /^[a-z]{2}(?:-[a-z0-9]{2,8})*$/.test(s)?s:null;
}
function languageName(code){return {en:'English',ja:'Japanese',zh:'Chinese',ko:'Korean',hi:'Hindi',es:'Spanish',fr:'French',de:'German',pt:'Portuguese',ru:'Russian',ar:'Arabic',it:'Italian',ta:'Tamil',te:'Telugu'}[String(code||'').split('-')[0]]||code;}
function hlsAttributes(line){var out={},re=/([A-Z0-9-]+)=(?:"([^"]*)"|([^,]*))/g,m;while((m=re.exec(line)))out[m[1]]=m[2]!=null?m[2]:m[3];return out;}
function playlistLanguages(body){
  var tracks=String(body).split(/\r?\n/).filter(function(l){return l.indexOf('#EXT-X-MEDIA:')===0;}).map(hlsAttributes).filter(function(t){return t.TYPE==='AUDIO';});
  return unique(tracks.map(function(t){return languageCode(t.LANGUAGE)||languageCode(t.NAME);}).filter(Boolean),function(x){return x;});
}
async function audioMetadata(streams){
  var override=setting('audioLanguage');
  return Promise.all(streams.map(async function(s){
    var known=languageCode(s.audioLang),langs=[];
    if(override&&override!=='auto')known=override;
    else if(s.container==='hls')try{var r=await fetch(s.url,{headers:s.headers||{},timeoutMs:4000});if(r.status>=200&&r.status<300)langs=playlistLanguages(r.body!=null?r.body:await r.text());}catch(e){/* Metadata is optional; never discard a playable stream. */}
    if(langs.length===1)known=langs[0];else if(langs.length>1)known=null;
    s.audioLang=known||null;
    var label=langs.length>1?'Audio: '+langs.map(languageName).join(', '):known?'Audio: '+languageName(known):'Audio: unspecified';
    s.label=(s.label||'Stream')+' · '+label;
    return s;
  }));
}

// SPDX-License-Identifier: Apache-2.0
// Read at call time: Zangetsu can update settings without reloading the source.
function setting(key) {
  var schema=getSettings().filter(function(s){return s.key===key;})[0];
  if(!schema)return undefined;
  var id=typeof __SOURCE_ID==='string'?__SOURCE_ID:SOURCE_ID;
  var saved=typeof __settings==='object'&&__settings[id]||{}, value=saved[key];
  if(schema.type==='bool')return typeof value==='boolean'?value:schema.default;
  if(schema.type==='enum')return schema.options.some(function(o){return o.value===value;})?value:schema.default;
  if(schema.type==='multiEnum')return Array.isArray(value)?value.filter(function(v){return schema.options.some(function(o){return o.value===v;});}):schema.default.slice();
  return typeof value==='string'?value:schema.default;
}
function choice(key,label,values,initial){return {key:key,label:label,type:'enum',default:initial,options:values.map(function(v){return {value:v[0],label:v[1]};})};}
function getSettings(){
  var out=[choice('audioLanguage','Audio language (when missing or incorrect)',[['auto','Detect automatically'],['en','English'],['ja','Japanese'],['zh','Chinese'],['ko','Korean'],['hi','Hindi'],['es','Spanish'],['fr','French'],['de','German'],['pt','Portuguese'],['ru','Russian'],['ar','Arabic']],'auto'),choice('timeout','Request timeout',[['8000','8 seconds'],['12000','12 seconds']],'12000')];
  if(TYPE==='anime')out=out.concat([
    choice('audio','Episode audio',[['both','Sub and dub'],['sub','Sub only'],['dub','Dub only']],'both'),
    {key:'subtitles',label:'Include subtitle tracks',type:'bool',default:true}
  ]);
  if(TYPE==='anime')out.push(choice('homeOrder','Show first on home',[['popular','Popular'],['latest','Latest updates']],'popular'));
  if(TYPE==='movie')out=out.concat([
    choice('streamServer','Stream servers',[['all','All available'],['1','Server 1'],['2','Server 2'],['3','Server 3']],'all'),
    choice('sameTitle','When a movie and series share a title',[['series','Prefer series'],['movie','Prefer movie']],'series'),
    choice('catalog','Browse and search',[['both','Movies and series'],['movie','Movies'],['series','Series']],'both'),
    {key:'subtitles',label:'Include subtitle tracks',type:'bool',default:true}
  ]);
  return out;
}
function homeOrder(rows){return setting('homeOrder')==='latest'?rows.slice().reverse():rows;}

// AES-256-CBC for the public MegaPlay response format; no remote script execution.
function decodePlayerSources(encoded) {
  var alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', raw=String(encoded).replace(/-/g,'+').replace(/_/g,'/').replace(/=+$/,''), bytes=[],bits=0,value=0;
  for(var i=0;i<raw.length;i++){var n=alphabet.indexOf(raw[i]);if(n<0)throw new Error('Invalid encrypted source');value=(value<<6)|n;bits+=6;if(bits>=8){bits-=8;bytes.push((value>>bits)&255);}}
  if(!bytes.length||bytes.length%16)throw new Error('Invalid encrypted source length');
  function mul(a,b){var r=0;while(b){if(b&1)r^=a;a=((a<<1)^((a&128)?283:0))&255;b>>=1;}return r;}
  function pow(a,n){var r=1;while(n){if(n&1)r=mul(r,a);a=mul(a,a);n>>=1;}return r;}
  function rot(a,n){return ((a<<n)|(a>>(8-n)))&255;}
  var s=[],inv=[];for(i=0;i<256;i++){var v=i?pow(i,254):0;s[i]=v^rot(v,1)^rot(v,2)^rot(v,3)^rot(v,4)^99;inv[s[i]]=i;}
  var key=utf8('i?LMTAx0Q6,:}50U');while(key.length<32)key.push(0);var rc=1;
  for(i=32;i<240;i+=4){var t=key.slice(i-4,i);if(i%32===0){t.push(t.shift());t=t.map(function(x){return s[x];});t[0]^=rc;rc=mul(rc,2);}else if(i%32===16)t=t.map(function(x){return s[x];});for(var j=0;j<4;j++)key[i+j]=key[i-32+j]^t[j];}
  var prev=utf8("W0;27ToaUpl_P%'c"),out=[];
  for(var off=0;off<bytes.length;off+=16){var a=bytes.slice(off,off+16);function add(round){for(var k=0;k<16;k++)a[k]^=key[round*16+k];}add(14);
    for(var round=13;round>=0;round--){var shifted=a.slice();for(var row=0;row<4;row++)for(var col=0;col<4;col++)a[col*4+row]=inv[shifted[((col-row+4)%4)*4+row]];add(round);if(round){for(col=0;col<4;col++){var q=a.slice(col*4,col*4+4);a[col*4]=mul(q[0],14)^mul(q[1],11)^mul(q[2],13)^mul(q[3],9);a[col*4+1]=mul(q[0],9)^mul(q[1],14)^mul(q[2],11)^mul(q[3],13);a[col*4+2]=mul(q[0],13)^mul(q[1],9)^mul(q[2],14)^mul(q[3],11);a[col*4+3]=mul(q[0],11)^mul(q[1],13)^mul(q[2],9)^mul(q[3],14);}}}
    for(j=0;j<16;j++)out.push(a[j]^prev[j]);prev=bytes.slice(off,off+16);
  }
  var pad=out[out.length-1];if(pad<1||pad>16||out.slice(-pad).some(function(x){return x!==pad;}))throw new Error('Invalid source encryption padding');out.length-=pad;
  return JSON.parse(decodeURIComponent(out.map(function(x){return '%'+('0'+x.toString(16)).slice(-2);}).join('')));
}
function sourceFiles(data){var v=data.sources;if(!v&&data.enc)v=decodePlayerSources(data.enc);if(!Array.isArray(v))v=[v];return v.map(function(x){return typeof x==='string'?x:x&&x.file;}).filter(function(x){return typeof x==='string'&&/^https?:\/\//i.test(x);});}
// SHA-256 operates on bytes, including HMAC's non-UTF8 pads.
function sha256Bytes(input){
 var primes=[],constants=[],initial=[];for(var n=2;primes.length<64;n++){if(primes.every(function(p){return n%p!==0;})){primes.push(n);constants.push((Math.pow(n,1/3)*4294967296)|0);if(initial.length<8)initial.push((Math.sqrt(n)*4294967296)|0);}}
 var bytes=input.slice(),length=bytes.length*8;bytes.push(128);while(bytes.length%64!==56)bytes.push(0);for(var i=7;i>=0;i--)bytes.push(i>=4?0:(length>>>(i*8))&255);
 function rotate(x,n){return(x>>>n)|(x<<(32-n));}var h=initial;
 for(var offset=0;offset<bytes.length;offset+=64){var w=[];for(i=0;i<16;i++)w[i]=(bytes[offset+4*i]<<24)|(bytes[offset+4*i+1]<<16)|(bytes[offset+4*i+2]<<8)|bytes[offset+4*i+3];for(i=16;i<64;i++){var x=w[i-15],y=w[i-2];w[i]=(w[i-16]+(rotate(x,7)^rotate(x,18)^(x>>>3))+w[i-7]+(rotate(y,17)^rotate(y,19)^(y>>>10)))|0;}var a=h.slice();for(i=0;i<64;i++){var t1=(a[7]+(rotate(a[4],6)^rotate(a[4],11)^rotate(a[4],25))+((a[4]&a[5])^(~a[4]&a[6]))+constants[i]+w[i])|0;var t2=((rotate(a[0],2)^rotate(a[0],13)^rotate(a[0],22))+((a[0]&a[1])^(a[0]&a[2])^(a[1]&a[2])))|0;a=[(t1+t2)|0,a[0],a[1],a[2],(a[3]+t1)|0,a[4],a[5],a[6]];}h=h.map(function(v,j){return(v+a[j])|0;});}
 var out=[];h.forEach(function(v){for(var j=3;j>=0;j--)out.push((v>>>(j*8))&255);});return out;
}
function signPlayerUrl(url,now){
 if(/[?&]token=/.test(url))return url;var match=url.match(/\/([a-f0-9]{32})\/([a-f0-9]{32})\//i);if(!match)return url;
 var message=String(Math.floor((now==null?Date.now():now)/1000)+90)+'|'+match[1].toLowerCase()+'/'+match[2].toLowerCase();
 var key=utf8('MpCdnT0k3n!9f2K#xQ7vL5mR8wN1pY4s');while(key.length<64)key.push(0);
 var inner=key.map(function(b){return b^54;}),outer=key.map(function(b){return b^92;});var signature=sha256Bytes(outer.concat(sha256Bytes(inner.concat(utf8(message)))));
 return url+(url.indexOf('?')<0?'?':'&')+'token='+b64(utf8(message)).replace(/=+$/,'')+'.'+b64(signature).replace(/=+$/,'');
}


// SPDX-License-Identifier: Apache-2.0
// Adapted from Yuzono AnimeGG. Independent AnimeGG/vidcache video hosting.
var ggBaseSettings=getSettings;
getSettings=function(){return ggBaseSettings().filter(function(s){return s.key==='audio'||s.key==='timeout';});};
function ggCards(raw,searching,query){return all(html(raw),function(n){return has(n,searching?'mse':'fea');}).map(function(n){var a=searching?n:first(n,function(c){return c.tag==='a'&&c.a.href&&c.parent&&has(c.parent,'rightpop');}),im=first(n,function(c){return c.tag==='img';}),title=content(searching?first(n,function(c){return c.tag==='h2';}):a);if(!a||!a.a.href||!title)return null;
  var alt=content(first(n,function(c){return c.tag==='div'&&/^Alt Titles\s*:/i.test(content(c))&&!first(c,function(x){return x.tag==='div';});}));
  var aliases=alt.replace(/^Alt Titles\s*:\s*/i,'').split(/[,;]/).map(function(s){return s.trim();});
  var match=aliases.filter(function(s){return query&&s.toLowerCase()===query.toLowerCase();})[0];
  return item(absolute(a.a.href,SITE),match||title,im?absolute(im.a.src,SITE):null);
}).filter(Boolean);}
async function search(query,page){return pageNum(page)>1?[]:ggCards(await request(SITE+'/search/?q='+encodeURIComponent(query)),true,String(query).trim());}
async function popular(page){return pageNum(page)>1?[]:ggCards(await request(SITE+'/popular-series?sortBy=hits&sortDirection=DESC&ongoing&limit=50&start=0'),false);}
async function getHome(){var p=await popular(1);return [{title:'Popular',items:p}];}
function ggEpisodes(raw){return unique(all(html(raw),function(n){return n.tag==='a'&&has(n,'anm_det_pop')&&n.a.href;}).map(function(n){var m=content(n).match(/(\d+(?:\.\d+)?)\s*$/);if(!m)return null;var u=absolute(n.a.href,SITE);return {id:pathOf(u),title:'Episode '+m[1],number:Number(m[1]),url:u};}).filter(Boolean),function(e){return e.id;}).sort(function(a,b){return a.number-b.number;});}
async function getEpisodes(url){return ggEpisodes(await request(url));}
async function getDetail(url){var raw=await request(url),root=html(raw),im=first(root,function(n){return n.tag==='img'&&has(n,'media-object');});var x=item(url,content(first(root,function(n){return n.tag==='h1';})),im?absolute(im.a.src,SITE):null);x.description=content(first(root,function(n){return has(n,'ptext');}));x.status=/Status:\s*Completed/i.test(content(root))?'completed':'unknown';x.episodes=ggEpisodes(raw);return x;}
function ggSources(raw){var m=raw.match(/var\s+videoSources\s*=\s*(\[[\s\S]*?\])\s*;/);if(!m)return [];return JSON.parse(m[1].replace(/([{,])\s*([A-Za-z_$][\w$]*)\s*:/g,'$1"$2":'));}
async function getVideoSources(url){var root=html(await request(url)),errors=[],groups=await Promise.all(all(root,function(n){return n.tag==='iframe'&&n.a.src;}).map(async function(n){try{var p=n.parent;while(p&&!has(p,'tab-pane'))p=p.parent;var mode=p&&p.a.id||'',kind=/dubbed/i.test(mode)?'dub':'sub';if(/raw/i.test(mode)||setting('audio')!=='both'&&setting('audio')!==kind)return [];var embed=absolute(n.a.src,url);return ggSources(await request(embed,url)).filter(function(v){return v.file;}).map(function(v){return {url:absolute(v.file,embed),label:'AnimeGG · '+kind+' · '+v.label,quality:v.label,container:'mp4',kind:kind,audioLang:kind==='dub'?'en':null,headers:{Referer:origin(embed)},subtitles:[]};});}catch(e){errors.push(e.message);return [];}}));var out=unique([].concat.apply([],groups),function(v){return v.url;}).sort(function(a,b){return parseInt(b.quality,10)-parseInt(a.quality,10);});if(!out.length)throw Error('AnimeGG: no playable streams. '+errors.join('; '));return out;}
