// SPDX-License-Identifier: Apache-2.0
// Modified for Zangetsu on 2026-09-15. See NOTICE.md for upstream credits.
// Generated by build.js; edit common.js and the corresponding *-core.js.
var SOURCE_ID="serenity-anikoto", NAME="Anikoto", SITE="https://anikototv.to", TYPE="anime", VERSION="0.1.1";
// Shared runtime helpers. No Node, DOM, browser cookies or remote code execution.
function text(value) {
  return String(value || '').replace(/<[^>]*>/g, '')
    .replace(/&#x([\da-f]+);/gi, function(_, n) { return String.fromCodePoint(parseInt(n, 16)); })
    .replace(/&#(\d+);/g, function(_, n) { return String.fromCodePoint(+n); })
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
}
function attrs(raw) {
  var out = {}, re = /([^\s=<>/]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g, m;
  while ((m = re.exec(raw))) out[m[1].toLowerCase()] = text(m[2] != null ? m[2] : m[3] != null ? m[3] : m[4] || '');
  return out;
}
// Small non-executing tree parser for the HTML selectors used by these sources.
function html(raw) {
  var root = {tag: '#root', a: {}, children: [], parent: null}, stack = [root];
  var tokens = String(raw).match(/<!--[\s\S]*?-->|<script\b[^>]*>[\s\S]*?<\/script\s*>|<style\b[^>]*>[\s\S]*?<\/style\s*>|<\/?[a-zA-Z][^>]*>|[^<]+/g) || [];
  tokens.forEach(function(t) {
    if (/^<!--|^<(script|style)\b/i.test(t)) return;
    if (/^<\//.test(t)) {
      var end = t.match(/^<\/([^\s>]+)/)[1].toLowerCase();
      for (var i = stack.length - 1; i > 0; i--) if (stack[i].tag === end) { stack.length = i; break; }
      return;
    }
    var parent = stack[stack.length - 1];
    if (t.charAt(0) !== '<') { parent.children.push({tag:'#text', value:text(t), children:[], a:{}, parent:parent}); return; }
    var m = t.match(/^<([^\s/>]+)([\s\S]*?)\/?\s*>$/); if (!m) return;
    var node = {tag:m[1].toLowerCase(), a:attrs(m[2]), children:[], parent:parent}; parent.children.push(node);
    if (!/^(img|input|br|hr|meta|link|source|area|base|embed|param|track|wbr)$/.test(node.tag) && !/\/\s*>$/.test(t)) stack.push(node);
  });
  return root;
}
function all(node, predicate) {
  var out = []; function walk(n) { n.children.forEach(function(c) { if(predicate(c)) out.push(c); walk(c); }); } walk(node); return out;
}
function first(node, predicate) { return all(node, predicate)[0] || null; }
function has(node, cls) { return (' ' + (node.a.class || '') + ' ').indexOf(' ' + cls + ' ') >= 0; }
function content(node) { return node ? (node.tag === '#text' ? node.value : node.children.map(content).join(' ')).replace(/\s+/g,' ').trim() : ''; }
function origin(url) { var m=String(url).match(/^https?:\/\/[^/]+/i); if(!m) throw new Error('Expected HTTP URL'); return m[0]; }
function absolute(url, base) {
  url=text(url); if(/^https?:\/\//i.test(url)) return url;
  if(url.indexOf('//')===0) return 'https:'+url;
  if(!url || /^[a-z][a-z0-9+.-]*:/i.test(url)) throw new Error('Invalid source URL');
  var root=origin(base || SITE), path=url.charAt(0)==='/' ? url : String(base || SITE+'/').split(/[?#]/)[0].replace(/[^/]*$/,'')+url;
  if(/^https?:/.test(path)) path=path.slice(origin(path).length);
  var parts=[]; path.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});
  return root+parts.join('/');
}
function pathOf(url) { return String(url).replace(/^https?:\/\/[^/]+/i,'').split(/[?#]/)[0]; }
function pageNum(p) { p=Math.floor(Number(p)||1); return Math.max(1,p); }
function headers(ref) { return {Referer:ref || SITE+'/'}; }
async function request(url, ref, json) {
  var h=headers(ref); if(json){h.Accept='application/json, text/javascript, */*; q=0.01';h['X-Requested-With']='XMLHttpRequest';}
  var res=await fetch(url,{headers:h,timeoutMs:12000});
  if(res.status<200 || res.status>=300) throw new Error(NAME+': HTTP '+res.status+' from '+origin(url));
  var body=res.body != null ? res.body : await res.text();
  if(json){try{return JSON.parse(body);}catch(e){throw new Error(NAME+': source returned invalid JSON');}}
  if(/<title>\s*(Just a moment|Attention Required)/i.test(body)) throw new Error(NAME+': open the source in the app WebView to complete its browser check');
  return body;
}
function unique(items, key) { var seen={}; return items.filter(function(x){var k=key(x);if(seen[k])return false;seen[k]=true;return true;}); }
function getInfo() { return {name:NAME,lang:'en',baseUrl:SITE,logo:SITE+'/favicon.ico',type:TYPE,version:VERSION}; }
function item(url,title,cover) { return {id:pathOf(url),title:title,url:url,cover:cover || null,coverHeaders:headers(),type:TYPE,sourceId:SOURCE_ID}; }

// AES-256-CBC for the public MegaPlay response format; no remote script execution.
function decodePlayerSources(encoded) {
  var alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', raw=String(encoded).replace(/-/g,'+').replace(/_/g,'/').replace(/=+$/,''), bytes=[],bits=0,value=0;
  for(var i=0;i<raw.length;i++){var n=alphabet.indexOf(raw[i]);if(n<0)throw new Error('Invalid encrypted source');value=(value<<6)|n;bits+=6;if(bits>=8){bits-=8;bytes.push((value>>bits)&255);}}
  if(!bytes.length||bytes.length%16)throw new Error('Invalid encrypted source length');
  function mul(a,b){var r=0;while(b){if(b&1)r^=a;a=((a<<1)^((a&128)?283:0))&255;b>>=1;}return r;}
  function pow(a,n){var r=1;while(n){if(n&1)r=mul(r,a);a=mul(a,a);n>>=1;}return r;}
  function rot(a,n){return ((a<<n)|(a>>(8-n)))&255;}
  var s=[],inv=[];for(i=0;i<256;i++){var v=i?pow(i,254):0;s[i]=v^rot(v,1)^rot(v,2)^rot(v,3)^rot(v,4)^99;inv[s[i]]=i;}
  var key=utf8('i?LMTAx0Q6,:}50U');while(key.length<32)key.push(0);var rc=1;
  for(i=32;i<240;i+=4){var t=key.slice(i-4,i);if(i%32===0){t.push(t.shift());t=t.map(function(x){return s[x];});t[0]^=rc;rc=mul(rc,2);}else if(i%32===16)t=t.map(function(x){return s[x];});for(var j=0;j<4;j++)key[i+j]=key[i-32+j]^t[j];}
  var prev=utf8("W0;27ToaUpl_P%'c"),out=[];
  for(var off=0;off<bytes.length;off+=16){var a=bytes.slice(off,off+16);function add(round){for(var k=0;k<16;k++)a[k]^=key[round*16+k];}add(14);
    for(var round=13;round>=0;round--){var shifted=a.slice();for(var row=0;row<4;row++)for(var col=0;col<4;col++)a[col*4+row]=inv[shifted[((col-row+4)%4)*4+row]];add(round);if(round){for(col=0;col<4;col++){var q=a.slice(col*4,col*4+4);a[col*4]=mul(q[0],14)^mul(q[1],11)^mul(q[2],13)^mul(q[3],9);a[col*4+1]=mul(q[0],9)^mul(q[1],14)^mul(q[2],11)^mul(q[3],13);a[col*4+2]=mul(q[0],13)^mul(q[1],9)^mul(q[2],14)^mul(q[3],11);a[col*4+3]=mul(q[0],11)^mul(q[1],13)^mul(q[2],9)^mul(q[3],14);}}}
    for(j=0;j<16;j++)out.push(a[j]^prev[j]);prev=bytes.slice(off,off+16);
  }
  var pad=out[out.length-1];if(pad<1||pad>16||out.slice(-pad).some(function(x){return x!==pad;}))throw new Error('Invalid source encryption padding');out.length-=pad;
  return JSON.parse(decodeURIComponent(out.map(function(x){return '%'+('0'+x.toString(16)).slice(-2);}).join('')));
}
function sourceFiles(data){var v=data.sources;if(!v&&data.enc)v=decodePlayerSources(data.enc);if(!Array.isArray(v))v=[v];return v.map(function(x){return typeof x==='string'?x:x&&x.file;}).filter(function(x){return typeof x==='string'&&/^https?:\/\//i.test(x);});}

// Port of Yuzono AnikotoTheme / AnikotoExtractor (Apache-2.0); see NOTICE.md.
function b64(bytes) {
  var chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_', out='';
  for(var i=0;i<bytes.length;i+=3){var a=bytes[i],b=bytes[i+1],c=bytes[i+2];out+=chars[a>>2]+chars[((a&3)<<4)|((b||0)>>4)]+(b==null?'=':chars[((b&15)<<2)|((c||0)>>6)])+(c==null?'=':chars[c&63]);}return out;
}
function utf8(s) { var b=unescape(encodeURIComponent(s));return b.split('').map(function(c){return c.charCodeAt(0);}); }
function rc4(key,s) { var a=[],j=0,t,out=[],bytes=utf8(s);for(var i=0;i<256;i++)a[i]=i;for(i=0;i<256;i++){j=(j+a[i]+key.charCodeAt(i%key.length))%256;t=a[i];a[i]=a[j];a[j]=t;}i=0;j=0;bytes.forEach(function(b){i=(i+1)%256;j=(j+a[i])%256;t=a[i];a[i]=a[j];a[j]=t;out.push(b^a[(a[i]+a[j])%256]);});return b64(out); }
function exchange(s,a,b){return s.split('').map(function(c){var i=a.indexOf(c);return i<0?c:b.charAt(i);}).join('');}
function vrf(s){s=exchange(s,'AP6GeR8H0lwUz1','UAz8Gwl10P6ReH');s=rc4('ItFKjuWokn4ZpB',s);s=rc4('fOyt97QWFB3',s);s=exchange(s,'1majSlPQd2M5','da1l2jSmP5QM');s=exchange(s,'CPYvHj09Au3','0jHA9CPYu3v');s=rc4('736y1uTJpBLUX',s.split('').reverse().join(''));return encodeURIComponent(b64(utf8(s)));}
function parseCatalogue(body){
  var doc=html(body), cards=all(doc,function(n){return n.tag==='div' && has(n,'item') && n.parent && has(n.parent,'ani') && has(n.parent,'items');});
  return unique(cards.map(function(n){var a=first(n,function(x){return x.tag==='a'&&has(x,'name');}),img=first(n,function(x){return x.tag==='img';});if(!a||!a.a.href)return null;var u=absolute(a.a.href,SITE+'/').replace(/\/ep-\d+(?:[?#].*)?$/,'');return item(u,content(a),img?absolute(img.a['data-src']||img.a.src,SITE+'/'):null);}).filter(Boolean),function(x){return x.id;});
}
async function search(query,page){query=String(query||'');return parseCatalogue(await request(SITE+'/filter?keyword='+encodeURIComponent(query)+'&page='+pageNum(page)+'&vrf='+(query?encodeURIComponent(vrf(query)):'')));}
async function popular(page){return parseCatalogue(await request(SITE+'/most-viewed/?page='+pageNum(page)));}
async function getHome(){return [{title:'Popular',items:await popular(1)},{title:'Latest updates',items:parseCatalogue(await request(SITE+'/latest-updated/?page=1'))}];}
function seriesUrl(url){return absolute(url,SITE+'/').split('#')[0].split('?')[0].replace(/\/ep-\d+$/,'');}
async function getDetail(url){
  url=seriesUrl(url);var doc=html(await request(url)),t=first(doc,function(n){return /^(h1|h2)$/.test(n.tag)&&has(n,'title');});if(!t)throw new Error(NAME+': title not found; site markup may have changed');
  var image=first(doc,function(n){return n.tag==='img' && n.parent && has(n.parent,'poster');});
  var syn=first(doc,function(n){return has(n,'synopsis');}), status=content(doc), result=item(url,content(t),image?absolute(image.a['data-src']||image.a.src,url):null);
  result.description=content(syn);result.status=/finished airing|completed/i.test(status)?'completed':/currently airing|ongoing anime/i.test(status)?'ongoing':'unknown';result.genres=[];result.studios=[];
  result.episodes=await episodesFromDocument(url,doc);return result;
}
async function getEpisodes(url){url=seriesUrl(url);return episodesFromDocument(url,html(await request(url)));}
async function episodesFromDocument(url,doc){
  var node=first(doc,function(n){return !!n.a['data-id'];})||first(doc,function(n){return !!n.a['data-tip'];});
  if(!node)throw new Error(NAME+': anime ID missing');var id=node.a['data-id']||node.a['data-tip'];
  var data=await request(SITE+'/ajax/episode/list/'+encodeURIComponent(id)+'?vrf='+vrf(id),url,true);
  var markup=typeof data.result==='string'?data.result:data.result&&data.result.html;if(typeof markup!=='string')throw new Error(NAME+': invalid episode response');
  return unique(all(html(markup),function(n){return n.tag==='a'&&!!n.a['data-ids'];}).map(function(n){
    var num=n.a['data-num'],title=n.parent?content(first(n.parent,function(x){return has(x,'d-title');})):'';
    var info={ids:n.a['data-ids'],epurl:pathOf(url)+'/ep-'+num,mal:n.a['data-mal']||'',slug:n.a['data-slug']||'',ts:n.a['data-timestamp']||''};
    var ep={id:pathOf(url)+':'+num,title:'Episode '+num+(title&&title!=='Episode '+num?': '+title:''),number:isFinite(Number(num))?Number(num):null,url:url+'#zangetsu='+encodeURIComponent(JSON.stringify(info)),filler:has(n,'filler')};
    if(info.ts&&isFinite(Number(info.ts)))ep.date=new Date(Number(info.ts)*1000).toISOString();return ep;
  }),function(x){return x.id;}).sort(function(a,b){return (a.number||0)-(b.number||0);});
}
function serverNodes(markup){return all(html(markup),function(n){return n.tag==='li'&&!!n.a['data-link-id']&&!has(n,'download-icon');}).map(function(n){var p=n.parent;while(p&&!has(p,'type'))p=p.parent;var label=p?content(first(p,function(x){return x.tag==='label';}))||p.a['data-type']||'sub':'sub';return {id:n.a['data-link-id'],name:content(n),kind:/dub/i.test(label)?'dub':'sub'};});}
function stream(url,server,ref,tracks){return {url:absolute(url,ref),label:server.name+' · '+server.kind,container:/\.mp4(?:[?#]|$)/i.test(url)?'mp4':'hls',kind:server.kind,headers:{Referer:ref,Origin:origin(ref)},subtitles:(tracks||[]).filter(function(t){return t.kind==='captions'&&t.file;}).map(function(t){return {url:absolute(t.file,ref),lang:t.label||'und',label:t.label||'Subtitles',format:/\.srt(?:[?#]|$)/i.test(t.file)?'srt':'vtt'};})};}
async function resolveEmbed(url,server,ref,depth){
  if(depth>3)throw new Error('Too many nested players');url=absolute(url,ref);
  // These upstream routes require Android's binary-rewriting local proxy.
  if(/kiwi|vidplay/i.test(server.name)||/mewcdn\.online\/player\/plyr\.php/i.test(url))throw new Error(server.name+': requires Android-only segment proxy');
  if(/\.m3u8(?:[?#]|$)|\.mp4(?:[?#]|$)/i.test(url)&&url.indexOf('/stream/')<0)return [stream(url,server,ref)];
  var body=await request(url,ref),host=origin(url),m=body.match(/data-id=["']([^"']+)["']/i);
  if(m){
    var type=(url.split(/[?#]/)[0].match(/\/(sub|dub|hsub)$/)||[])[1]||'',id=encodeURIComponent(m[1]);
    // getSourcesNew requires byte-rewriting proxy and is deliberately not advertised.
    var api=await request(host+'/stream/getSources?id='+id+'&id='+id+'&type='+type+'&type='+type,url,true);
    var files=sourceFiles(api);if(!files.length)throw new Error(server.name+': direct stream missing; proxy-only or changed API');
    return files.map(function(file){return stream(file,server,host+'/',api.tracks);});
  }
  m=body.match(/<iframe[^>]+src=["']([^"']+)["']/i);if(m)return resolveEmbed(m[1],server,url,depth+1);
  m=body.match(/https?:\/\/[^\s"'<>]+\.m3u8[^\s"'<>]*/i);if(m)return [stream(text(m[0]),server,host+'/')];
  m=body.match(/<source[^>]+src=["']([^"']+)["']/i);if(m)return [stream(m[1],server,host+'/')];
  throw new Error(server.name+': no supported direct stream found');
}
async function getVideoSources(episodeUrl){
  var marker=String(episodeUrl).split('#zangetsu=')[1];if(!marker)throw new Error('Refresh the episode list before playing');var ep=JSON.parse(decodeURIComponent(marker));
  var ref=SITE+ep.epurl,data=await request(SITE+'/ajax/server/list?servers='+encodeURIComponent(ep.ids),ref,true);
  var markup=typeof data.result==='string'?data.result:data.result&&data.result.html;if(typeof markup!=='string')throw new Error('Invalid server list');
  var servers=serverNodes(markup),out=[],failures=[];
  // Resolve a bounded set, two at a time; one dead mirror must not freeze the app.
  var candidates=servers.filter(function(s){return !/kiwi|vidplay/i.test(s.name);}).slice(0,6);
  for(var i=0;i<candidates.length;i+=2){var batch=await Promise.all(candidates.slice(i,i+2).map(async function(s){try{var r=await request(SITE+'/ajax/server?get='+encodeURIComponent(s.id),ref,true);if(!r.result||!r.result.url)throw new Error('Missing embed URL');return await resolveEmbed(r.result.url,s,ref,0);}catch(e){failures.push(s.name+': '+e.message);return [];}}));batch.forEach(function(v){out=out.concat(v);});if(out.some(function(v){return v.kind==='sub';})&&out.some(function(v){return v.kind==='dub';}))break;}
  if(!out.length)throw new Error(NAME+': no supported direct servers. '+(failures.join('; ')||'Available hosts require the Android proxy.'));
  return unique(out,function(v){return v.url+'|'+v.kind;});
}


