const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
let calls=[],saved={};const c={__settings:{'serenity-animedex':saved},fetch:async(u,o={})=>{calls.push({u,o});if(o.method==='HEAD')return {status:200,headers:{'content-length':'0'},body:''};if(u.includes('cdn.example'))return {status:200,body:u.includes('ad-page')?'<html>Ad</html>':'#EXTM3U\n#EXTINF:2,\nsegment.ts'};return {status:200,body:JSON.stringify(u.includes('/episodes/')?{episodes:[{number:2},{number:1},{number:1}]}:{anime:{info:{id:'test-123',anilistId:123,name:'Test',genres:['Action'],status:'FINISHED'}}})}}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','serenity-animedex.js'),'utf8'),c);
(async()=>{
 const d=await c.getDetail('https://animedex.fun/anime/test-123');assert.equal(d.episodes.length,2);assert.equal(d.episodes[0].number,1);assert.equal(calls[0].o.headers['User-Agent'],'Mozilla/5.0');
 const names=Array.from(c.dexServers,s=>s[1]);assert.equal(names.length,10);assert.equal(names[0],'VidNest Embed');assert.equal(names[9],'Draco Luna');
 assert.equal(c.dexStreams({sources:[{url:'https://cdn.example/test.m3u8',isHLS:true}],subtitles:[],tracks:[{file:'https://cdn.example/en.vtt',label:'English',kind:'captions'}]},c.dexServers[5],'sub')[0].subtitles.length,1);
 assert.equal(await c.dexPlayable({url:'https://cdn.example/empty.mp4',headers:{},container:'mp4'}),false);
 const originalResolve=c.dexResolve;let resolved=[];
 c.dexResolve=async(s,ep,kind)=>{resolved.push([s[0],kind]);if(s[0]==='anibd')throw Error('upstream unavailable');return {sources:[{url:'https://cdn.example/'+s[0]+'/'+kind+'.m3u8',isHLS:true}],subtitles:[{url:'https://cdn.example/de.vtt',label:'German',language:'en'}]};};
 let streams=await c.getVideoSources(d.episodes[0].url);assert.equal(resolved.length,18);assert.equal(streams.length,17);assert.equal(streams[0].label,'AnimeDex · VidNest Embed · sub');assert.equal(streams[2].label,'AnimeDex · VidNest Pahe Embed · sub');assert.equal(streams[0].subtitles[0].lang,'de');assert.equal(streams[1].audioLang,'en');assert(!resolved.some(([s,k])=>s==='anibd'&&k==='dub'));
 saved.dexEnableAll=false;saved.dexSelected=['megaplay'];saved.audio='dub';saved.subtitles=false;resolved=[];streams=await c.getVideoSources(d.episodes[0].url);assert.equal(streams.length,1);assert.equal(resolved.length,1);assert.equal(streams[0].subtitles.length,0);
 saved.dexSelected=[];await assert.rejects(()=>c.getVideoSources(d.episodes[0].url),/select a server/);saved.dexEnableAll=true;streams=await c.getVideoSources(d.episodes[0].url);assert(streams.length>1);
 assert.equal(await c.dexPlayable({url:'https://cdn.example/ad-page.m3u8',headers:{},container:'hls'}),false);
 assert.equal(c.dexStreams({sources:[{url:'https://embed.example/page'}]},c.dexServers[0],'sub').length,0);
 assert.equal(c.dexStreams({sources:[{url:'https://api.luna-stream.me/proxy?url=%2Fapi%2Finternal%2Ftest.m3u8',isHLS:true}]},c.dexServers.find(s=>s[0]==='anilink'),'sub').length,0);
 c.dexResolve=originalResolve;calls=[];await c.dexResolve(c.dexServers.find(s=>s[0]==='mf-aniwaves'),{id:123,ep:2},'dub');assert.deepEqual(JSON.parse(calls[0].o.body),{anilistId:123,ep:2,lang:'dub',action:'aniwaves'});
 calls=[];await c.dexResolve(c.dexServers.find(s=>s[0]==='avx-anikoto'),{id:123,ep:2},'sub');assert.equal(JSON.parse(calls[0].o.body).provider,'anikoto');
 calls=[];await c.dexResolve(c.dexServers.find(s=>s[0]==='megaplay'),{id:123,ep:2},'dub');assert.equal(JSON.parse(calls[0].o.body).subType,'dub');
 await assert.rejects(()=>c.getVideoSources('bad'),/refresh/);
 console.log('PASS: 10 verified ordered settings, enable-all override, custom selection, audio, failure isolation, headers, API mapping, caption language, ad/HTML and internal-link rejection.');
})().catch(e=>{console.error(e);process.exitCode=1});
