const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
function load(handler,settings={}){const calls=[],c={__SOURCE_ID:'installed-streamplay',__settings:{'installed-streamplay':settings},fetch:async(u,o={})=>{calls.push({u,o});if(o.method==='HEAD')return {status:200,body:''};return {status:200,body:JSON.stringify(await handler(u,o))};}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','serenity-streamplay.js'),'utf8'),c);c.calls=calls;return c;}
const ep={id:'tt1196946',tmdb:5920,type:'series',title:'The Mentalist',season:2,episode:3};
const url='https://v3-cinemeta.strem.io/meta/series/tt1196946.json#cine='+encodeURIComponent(JSON.stringify(ep));
(async()=>{
 const c=load((u,o)=>{if(u.includes('/enc-vidlink'))return {status:200,result:'a/b+c='};if(u.includes('vidlink.pro'))return {stream:{type:'file',qualities:{720:{url:'https://cdn.example/video.mp4?sign=keep&t=123',headers:{Referer:'https://player.example/',Origin:'https://player.example'}},1080:{url:'https://cdn.example/hd.mp4?sign=also-keep',headers:{}}},captions:[{url:'https://cdn.example/en.srt',language:'English'}]}};throw Error('fallback unavailable');});
 const out=await c.getVideoSources(url);assert.equal(out.length,2);assert.equal(out[0].quality,'1080');assert.equal(out[1].url,'https://cdn.example/video.mp4?sign=keep&t=123');assert.equal(out[1].headers.Referer,'https://player.example/');assert.equal(out[1].subtitles[0].lang,'en');assert.equal(out[1].subtitles[0].format,'srt');assert.equal(out[1].container,'mp4');assert(c.calls.some(x=>x.u.endsWith('/tv/a%2Fb%2Bc%3D/2/3')));assert(!c.getSettings().some(x=>x.key==='streamServer'));
 const v=load(u=>{assert(u.includes('tmdb=5920&type=tv&season=2&episode=3'));return {data:{stream_urls:['https://cdn.example/master.m3u8'],default_subs:[]}};},{backend:'vaplayer',audioLanguage:'en'});let rows=await v.getVideoSources(url);assert.equal(rows[0].audioLang,'en');assert(!v.calls.some(x=>x.u.includes('vidlink')));
 const f=load(()=>{throw Error('offline');});await assert.rejects(()=>f.getVideoSources(url),/vidlink: offline.*vaplayer: offline/);await assert.rejects(()=>c.getVideoSources(url.replace('season%22%3A2','season%22%3A0')),/invalid episode/);
 const legacy=c.spVidlinkStreams({stream:{playlist:'https://proxy.example/master.m3u8?token=keep&headers='+encodeURIComponent(JSON.stringify({Referer:'https://old.example/'})),captions:[]}});assert(legacy[0].url.includes('token=keep'));assert.equal(legacy[0].headers.Referer,'https://old.example/');
 assert.equal(c.spVidlinkStreams({stream:{qualities:{720:{url:'javascript:bad'}}}}).length,0);assert.equal(c.spHeaders({'X-Test':'bad\r\nInjected: true'} )['X-Test'],undefined);
 const health=load(()=>({}));health.fetch=async(u)=>({status:u.includes('dead')?429:200,body:''});assert.equal((await health.spAvailable([{url:'https://cdn.example/dead'},{url:'https://cdn.example/ok'}])).length,1);
 console.log('PASS: StreamPlay TV mapping, signed URL preservation, quality ordering, captions, headers, backend settings, failure isolation and legacy playlist.');
})().catch(e=>{console.error(e);process.exitCode=1;});
